-DARDUINO=181
-I "D:/Program Files (x86)/Labcenter Electronics/Proteus 8 Professional/Tools/Arduino/hardware/arduino/avr/cores/arduino"
-I "D:/Program Files (x86)/Labcenter Electronics/Proteus 8 Professional/Tools/Arduino/hardware/arduino/avr/variants/eightanaloginputs"
-I "D:/Program Files (x86)/Labcenter Electronics/Proteus 8 Professional/DATA/VSM Studio/drivers/Arduino/Core"
-I "D:/Program Files (x86)/Labcenter Electronics/Proteus 8 Professional/DATA/VSM Studio/drivers/Arduino/Cpu"

